const products = [
  {
    id: 1,
    title: "Elegant Red Dress",
    description: "A beautiful red dress for evening events.",
    price: 49.99,
    new: true,
    category: "Women's-Clothing",
    image: "/images/dress.jpg",
  },
  {
    id: 2,
    title: "Summer Floral Dress",
    description: "A light floral dress perfect for the summer season.",
    price: 39.99,
    new: false,
    category: "Women's-Clothing",
    image: "/images/dress.jpg",
  },
  {
    id: 3,
    title: "Classic Blue Shirt",
    description: "A classic blue shirt for a smart casual look.",
    price: 29.99,
    new: true,
    category: "Men's-Clothing",
    image: "/images/dress.jpg",
  },
  {
    id: 4,
    title: "Casual White Shirt",
    description: "Comfortable white shirt for casual wear.",
    price: 19.99,
    new: false,
    category: "Men's-Clothing",
    image: "/images/dress.jpg",
  },
  {
    id: 5,
    title: "Sporty Running Shoes",
    description: "Comfortable running shoes designed for performance.",
    price: 59.99,
    new: true,
    category: "Men's-Footwear",
    image: "/images/dress.jpg",
  },
  {
    id: 6,
    title: "Classic Leather Boots",
    description: "Stylish leather boots for men that suit every occasion.",
    price: 89.99,
    new: false,
    category: "Men's-Footwear",
    image: "/images/dress.jpg",
  },
  {
    id: 7,
    title: "Summer Sandals",
    description: "Cool sandals for warm weather.",
    price: 39.99,
    new: true,
    category: "Women's-Footwear",
    image: "/images/dress.jpg",
  },
  {
    id: 8,
    title: "Winter Warm Boots",
    description: "Durable boots to keep your feet warm in winter.",
    price: 79.99,
    new: false,
    category: "Women's-Footwear",
    image: "/images/dress.jpg",
  },
  {
    id: 9,
    title: "Chic Black Dress",
    description: "Elegant black dress for any special occasion.",
    price: 69.99,
    new: true,
    category: "Women's-Clothing",
    image: "/images/dress.jpg",
  },
  {
    id: 10,
    title: "Luxury Evening Gown",
    description: "A luxurious gown for elegant evening events.",
    price: 129.99,
    new: false,
    category: "Women's-Clothing",
    image: "/images/dress.jpg",
  },
  {
    id: 11,
    title: "Slim Fit T-Shirt",
    description: "A slim fit t-shirt perfect for a modern look.",
    price: 25.99,
    new: true,
    category: "Men's-Clothing",
    image: "/images/dress.jpg",
  },
  {
    id: 12,
    title: "Graphic Tee",
    description: "Casual t-shirt with a cool graphic design.",
    price: 19.99,
    new: false,
    category: "Men's-Clothing",
    image: "/images/dress.jpg",
  },
  {
    id: 13,
    title: "Stylish High Heels",
    description: "High heels for women to make every outfit special.",
    price: 79.99,
    new: true,
    category: "Women's-Footwear",
    image: "/images/dress.jpg",
  },
  {
    id: 14,
    title: "Comfortable Ballet Flats",
    description: "Ballet flats for women, perfect for all-day wear.",
    price: 49.99,
    new: false,
    category: "Women's-Footwear",
    image: "/images/dress.jpg",
  },
  {
    id: 15,
    title: "Cozy Wool Sweater",
    description: "A warm and cozy sweater for the colder months.",
    price: 69.99,
    new: true,
    category: "Men's-Clothing",
    image: "/images/dress.jpg",
  },
  {
    id: 16,
    title: "Padded Winter Jacket",
    description: "A padded jacket designed for winter conditions.",
    price: 99.99,
    new: false,
    category: "Men's-Clothing",
    image: "/images/dress.jpg",
  },
  {
    id: 17,
    title: "Floral Print Blouse",
    description: "Light and breezy blouse with a floral print.",
    price: 34.99,
    new: true,
    category: "Women's-Clothing",
    image: "/images/dress.jpg",
  },
  {
    id: 18,
    title: "Black Leather Boots",
    description: "Stylish black leather boots for women.",
    price: 89.99,
    new: false,
    category: "Women's-Footwear",
    image: "/images/dress.jpg",
  },
  {
    id: 19,
    title: "Chukka Boots",
    description: "Stylish and casual chukka boots for men.",
    price: 75.99,
    new: true,
    category: "Men's-Footwear",
    image: "/images/dress.jpg",
  },
  {
    id: 20,
    title: "Chunky Sneakers",
    description: "Trendy chunky sneakers for a street style look.",
    price: 69.99,
    new: true,
    category: "Men's-Footwear",
    image: "/images/dress.jpg",
  },
];
export default products;
