const products = [
  // femmes
  {
    id: 1,
    title: "Robe rouge élégante",
    description: "Une belle robe rouge pour les soirées.",
    price: 49.99,
    new: true,
    category: "femmes",
    image: "/images/dress.jpg",
  },
  {
    id: 2,
    title: "Robe florale d'été",
    description: "Robe légère avec imprimé floral pour l'été.",
    price: 39.99,
    new: false,
    category: "femmes",
    image: "/images/dress.jpg",
  },
  {
    id: 3,
    title: "Robe noire chic",
    description: "Élégante robe noire pour les occasions spéciales.",
    price: 69.99,
    new: true,
    category: "femmes",
    image: "/images/dress.jpg",
  },
  {
    id: 4,
    title: "Robe de soirée luxueuse",
    description: "Robe somptueuse pour les soirées élégantes.",
    price: 129.99,
    new: false,
    category: "femmes",
    image: "/images/dress.jpg",
  },
  {
    id: 5,
    title: "Blouse à imprimé floral",
    description: "Blouse légère et aérienne avec un imprimé floral.",
    price: 34.99,
    new: true,
    category: "femmes",
    image: "/images/dress.jpg",
  },
  {
    id: 6,
    title: "Talons hauts élégants",
    description: "Talons pour sublimer toutes vos tenues.",
    price: 79.99,
    new: true,
    category: "femmes",
    image: "/images/dress.jpg",
  },
  {
    id: 7,
    title: "Ballerines confortables",
    description: "Ballerines parfaites pour une journée entière.",
    price: 49.99,
    new: false,
    category: "femmes",
    image: "/images/dress.jpg",
  },
  {
    id: 8,
    title: "Bottes en cuir noir",
    description: "Bottes stylées pour femmes.",
    price: 89.99,
    new: false,
    category: "femmes",
    image: "/images/dress.jpg",
  },
  {
    id: 9,
    title: "Sandales d'été",
    description: "Sandales légères pour temps chaud.",
    price: 39.99,
    new: true,
    category: "femmes",
    image: "/images/dress.jpg",
  },
  {
    id: 10,
    title: "Chemisier classique blanc",
    description: "Chemisier élégant pour toutes occasions.",
    price: 44.99,
    new: true,
    category: "femmes",
    image: "/images/dress.jpg",
  },

  // hommes
  {
    id: 11,
    title: "Chemise bleue classique",
    description: "Chemise bleue pour un look smart casual.",
    price: 29.99,
    new: true,
    category: "hommes",
    image: "/images/dress.jpg",
  },
  {
    id: 12,
    title: "Chemise blanche décontractée",
    description: "Chemise confortable pour un style relax.",
    price: 19.99,
    new: false,
    category: "hommes",
    image: "/images/dress.jpg",
  },
  {
    id: 13,
    title: "T-shirt slim fit",
    description: "T-shirt moulant pour un look moderne.",
    price: 25.99,
    new: true,
    category: "hommes",
    image: "/images/dress.jpg",
  },
  {
    id: 14,
    title: "T-shirt graphique",
    description: "T-shirt avec un design cool.",
    price: 19.99,
    new: false,
    category: "hommes",
    image: "/images/dress.jpg",
  },
  {
    id: 15,
    title: "Pull en laine",
    description: "Pull chaud pour les mois froids.",
    price: 69.99,
    new: true,
    category: "hommes",
    image: "/images/dress.jpg",
  },
  {
    id: 16,
    title: "Veste d'hiver matelassée",
    description: "Veste parfaite pour l'hiver.",
    price: 99.99,
    new: false,
    category: "hommes",
    image: "/images/dress.jpg",
  },
  {
    id: 17,
    title: "Bottes en cuir",
    description: "Bottes élégantes en cuir pour hommes.",
    price: 89.99,
    new: false,
    category: "hommes",
    image: "/images/dress.jpg",
  },
  {
    id: 18,
    title: "Chukka boots",
    description: "Chaussures décontractées stylées.",
    price: 75.99,
    new: true,
    category: "hommes",
    image: "/images/dress.jpg",
  },
  {
    id: 19,
    title: "Sneakers chunky",
    description: "Sneakers tendances pour un look urbain.",
    price: 69.99,
    new: true,
    category: "hommes",
    image: "/images/dress.jpg",
  },
  {
    id: 20,
    title: "Chaussures de course",
    description: "Chaussures confortables pour le sport.",
    price: 59.99,
    new: true,
    category: "hommes",
    image: "/images/dress.jpg",
  },

  // cuisine
  {
    id: 21,
    title: "Batterie de cuisine 10 pièces",
    description: "Ensemble complet pour la cuisine quotidienne.",
    price: 89.99,
    new: true,
    category: "cuisine",
    image: "/images/dress.jpg",
  },
  {
    id: 22,
    title: "Poêle antiadhésive",
    description: "Poêle parfaite pour cuisiner sans accrocher.",
    price: 29.99,
    new: true,
    category: "cuisine",
    image: "/images/dress.jpg",
  },
  {
    id: 23,
    title: "Set de couteaux professionnels",
    description: "Couteaux pour une coupe parfaite.",
    price: 59.99,
    new: false,
    category: "cuisine",
    image: "/images/dress.jpg",
  },
  {
    id: 24,
    title: "Mixeur électrique",
    description: "Mixeur puissant pour toutes préparations.",
    price: 49.99,
    new: true,
    category: "cuisine",
    image: "/images/dress.jpg",
  },
  {
    id: 25,
    title: "Planche à découper en bois",
    description: "Planche durable pour couper vos aliments.",
    price: 19.99,
    new: false,
    category: "cuisine",
    image: "/images/dress.jpg",
  },
  {
    id: 26,
    title: "Moule à gâteau",
    description: "Idéal pour les amateurs de pâtisserie.",
    price: 14.99,
    new: true,
    category: "cuisine",
    image: "/images/dress.jpg",
  },
  {
    id: 27,
    title: "Passoire inox",
    description: "Passoire robuste et facile à nettoyer.",
    price: 9.99,
    new: false,
    category: "cuisine",
    image: "/images/dress.jpg",
  },
  {
    id: 28,
    title: "Spatules en silicone",
    description: "Lot de 3 spatules résistantes à la chaleur.",
    price: 12.99,
    new: true,
    category: "cuisine",
    image: "/images/dress.jpg",
  },
  {
    id: 29,
    title: "Boîtes de conservation",
    description: "Idéales pour conserver les restes.",
    price: 24.99,
    new: false,
    category: "cuisine",
    image: "/images/dress.jpg",
  },
  {
    id: 30,
    title: "Râpe multifonction",
    description: "Pour râper, trancher et couper.",
    price: 17.99,
    new: true,
    category: "cuisine",
    image: "/images/dress.jpg",
  },

  // bébés
  {
    id: 31,
    title: "Pyjama bébé coton",
    description: "Pyjama doux pour le sommeil de bébé.",
    price: 19.99,
    new: true,
    category: "bébés",
    image: "/images/dress.jpg",
  },
  {
    id: 32,
    title: "Grenouillère rose",
    description: "Grenouillère chaude et confortable.",
    price: 24.99,
    new: false,
    category: "bébés",
    image: "/images/dress.jpg",
  },
  {
    id: 33,
    title: "Body manches longues",
    description: "Lot de 3 bodies en coton.",
    price: 29.99,
    new: true,
    category: "bébés",
    image: "/images/dress.jpg",
  },
  {
    id: 34,
    title: "Salopette en jean",
    description: "Salopette mignonne et résistante.",
    price: 34.99,
    new: false,
    category: "bébés",
    image: "/images/dress.jpg",
  },
  {
    id: 35,
    title: "Chaussettes pour bébé",
    description: "Lot de 5 paires colorées.",
    price: 9.99,
    new: true,
    category: "bébés",
    image: "/images/dress.jpg",
  },
  {
    id: 36,
    title: "Bavoir imperméable",
    description: "Bavoir pratique pour les repas.",
    price: 7.99,
    new: false,
    category: "bébés",
    image: "/images/dress.jpg",
  },
  {
    id: 37,
    title: "Bonnet en laine",
    description: "Bonnet chaud pour bébé.",
    price: 12.99,
    new: true,
    category: "bébés",
    image: "/images/dress.jpg",
  },
  {
    id: 38,
    title: "Pantalon bébé",
    description: "Pantalon souple et confortable.",
    price: 17.99,
    new: false,
    category: "bébés",
    image: "/images/dress.jpg",
  },
  {
    id: 39,
    title: "T-shirt bébé",
    description: "T-shirt doux à imprimé animalier.",
    price: 14.99,
    new: true,
    category: "bébés",
    image: "/images/dress.jpg",
  },
  {
    id: 40,
    title: "Combinaison polaire",
    description: "Pour garder bébé bien au chaud.",
    price: 39.99,
    new: true,
    category: "bébés",
    image: "/images/dress.jpg",
  },
];

export default products;
